// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/subscriptiondailyresetevent"
)

// SubscriptionDailyResetEvent is the model entity for the SubscriptionDailyResetEvent schema.
type SubscriptionDailyResetEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID int64 `json:"subscription_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// OperationID holds the value of the "operation_id" field.
	OperationID string `json:"operation_id,omitempty"`
	// RequestFingerprint holds the value of the "request_fingerprint" field.
	RequestFingerprint string `json:"request_fingerprint,omitempty"`
	// BeforeVersion holds the value of the "before_version" field.
	BeforeVersion int64 `json:"before_version,omitempty"`
	// AfterVersion holds the value of the "after_version" field.
	AfterVersion int64 `json:"after_version,omitempty"`
	// Timezone holds the value of the "timezone" field.
	Timezone string `json:"timezone,omitempty"`
	// CountDate holds the value of the "count_date" field.
	CountDate time.Time `json:"count_date,omitempty"`
	// DaySequence holds the value of the "day_sequence" field.
	DaySequence int `json:"day_sequence,omitempty"`
	// BeforeDailyUsageUsd holds the value of the "before_daily_usage_usd" field.
	BeforeDailyUsageUsd float64 `json:"before_daily_usage_usd,omitempty"`
	// AfterDailyUsageUsd holds the value of the "after_daily_usage_usd" field.
	AfterDailyUsageUsd float64 `json:"after_daily_usage_usd,omitempty"`
	// DailyLimitUsd holds the value of the "daily_limit_usd" field.
	DailyLimitUsd float64 `json:"daily_limit_usd,omitempty"`
	// BeforeExpiresAt holds the value of the "before_expires_at" field.
	BeforeExpiresAt time.Time `json:"before_expires_at,omitempty"`
	// AfterExpiresAt holds the value of the "after_expires_at" field.
	AfterExpiresAt time.Time `json:"after_expires_at,omitempty"`
	// DeductedSeconds holds the value of the "deducted_seconds" field.
	DeductedSeconds int `json:"deducted_seconds,omitempty"`
	// DecidedAt holds the value of the "decided_at" field.
	DecidedAt    time.Time `json:"decided_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionDailyResetEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptiondailyresetevent.FieldBeforeDailyUsageUsd, subscriptiondailyresetevent.FieldAfterDailyUsageUsd, subscriptiondailyresetevent.FieldDailyLimitUsd:
			values[i] = new(sql.NullFloat64)
		case subscriptiondailyresetevent.FieldID, subscriptiondailyresetevent.FieldSubscriptionID, subscriptiondailyresetevent.FieldUserID, subscriptiondailyresetevent.FieldGroupID, subscriptiondailyresetevent.FieldBeforeVersion, subscriptiondailyresetevent.FieldAfterVersion, subscriptiondailyresetevent.FieldDaySequence, subscriptiondailyresetevent.FieldDeductedSeconds:
			values[i] = new(sql.NullInt64)
		case subscriptiondailyresetevent.FieldSource, subscriptiondailyresetevent.FieldOperationID, subscriptiondailyresetevent.FieldRequestFingerprint, subscriptiondailyresetevent.FieldTimezone:
			values[i] = new(sql.NullString)
		case subscriptiondailyresetevent.FieldCountDate, subscriptiondailyresetevent.FieldBeforeExpiresAt, subscriptiondailyresetevent.FieldAfterExpiresAt, subscriptiondailyresetevent.FieldDecidedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionDailyResetEvent fields.
func (_m *SubscriptionDailyResetEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptiondailyresetevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case subscriptiondailyresetevent.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = value.Int64
			}
		case subscriptiondailyresetevent.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case subscriptiondailyresetevent.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case subscriptiondailyresetevent.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case subscriptiondailyresetevent.FieldOperationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation_id", values[i])
			} else if value.Valid {
				_m.OperationID = value.String
			}
		case subscriptiondailyresetevent.FieldRequestFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_fingerprint", values[i])
			} else if value.Valid {
				_m.RequestFingerprint = value.String
			}
		case subscriptiondailyresetevent.FieldBeforeVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field before_version", values[i])
			} else if value.Valid {
				_m.BeforeVersion = value.Int64
			}
		case subscriptiondailyresetevent.FieldAfterVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field after_version", values[i])
			} else if value.Valid {
				_m.AfterVersion = value.Int64
			}
		case subscriptiondailyresetevent.FieldTimezone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field timezone", values[i])
			} else if value.Valid {
				_m.Timezone = value.String
			}
		case subscriptiondailyresetevent.FieldCountDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field count_date", values[i])
			} else if value.Valid {
				_m.CountDate = value.Time
			}
		case subscriptiondailyresetevent.FieldDaySequence:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field day_sequence", values[i])
			} else if value.Valid {
				_m.DaySequence = int(value.Int64)
			}
		case subscriptiondailyresetevent.FieldBeforeDailyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field before_daily_usage_usd", values[i])
			} else if value.Valid {
				_m.BeforeDailyUsageUsd = value.Float64
			}
		case subscriptiondailyresetevent.FieldAfterDailyUsageUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field after_daily_usage_usd", values[i])
			} else if value.Valid {
				_m.AfterDailyUsageUsd = value.Float64
			}
		case subscriptiondailyresetevent.FieldDailyLimitUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_limit_usd", values[i])
			} else if value.Valid {
				_m.DailyLimitUsd = value.Float64
			}
		case subscriptiondailyresetevent.FieldBeforeExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field before_expires_at", values[i])
			} else if value.Valid {
				_m.BeforeExpiresAt = value.Time
			}
		case subscriptiondailyresetevent.FieldAfterExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field after_expires_at", values[i])
			} else if value.Valid {
				_m.AfterExpiresAt = value.Time
			}
		case subscriptiondailyresetevent.FieldDeductedSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deducted_seconds", values[i])
			} else if value.Valid {
				_m.DeductedSeconds = int(value.Int64)
			}
		case subscriptiondailyresetevent.FieldDecidedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field decided_at", values[i])
			} else if value.Valid {
				_m.DecidedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionDailyResetEvent.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionDailyResetEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SubscriptionDailyResetEvent.
// Note that you need to call SubscriptionDailyResetEvent.Unwrap() before calling this method if this SubscriptionDailyResetEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionDailyResetEvent) Update() *SubscriptionDailyResetEventUpdateOne {
	return NewSubscriptionDailyResetEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionDailyResetEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionDailyResetEvent) Unwrap() *SubscriptionDailyResetEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionDailyResetEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionDailyResetEvent) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionDailyResetEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("subscription_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("operation_id=")
	builder.WriteString(_m.OperationID)
	builder.WriteString(", ")
	builder.WriteString("request_fingerprint=")
	builder.WriteString(_m.RequestFingerprint)
	builder.WriteString(", ")
	builder.WriteString("before_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.BeforeVersion))
	builder.WriteString(", ")
	builder.WriteString("after_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.AfterVersion))
	builder.WriteString(", ")
	builder.WriteString("timezone=")
	builder.WriteString(_m.Timezone)
	builder.WriteString(", ")
	builder.WriteString("count_date=")
	builder.WriteString(_m.CountDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("day_sequence=")
	builder.WriteString(fmt.Sprintf("%v", _m.DaySequence))
	builder.WriteString(", ")
	builder.WriteString("before_daily_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.BeforeDailyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("after_daily_usage_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.AfterDailyUsageUsd))
	builder.WriteString(", ")
	builder.WriteString("daily_limit_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyLimitUsd))
	builder.WriteString(", ")
	builder.WriteString("before_expires_at=")
	builder.WriteString(_m.BeforeExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("after_expires_at=")
	builder.WriteString(_m.AfterExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deducted_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeductedSeconds))
	builder.WriteString(", ")
	builder.WriteString("decided_at=")
	builder.WriteString(_m.DecidedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionDailyResetEvents is a parsable slice of SubscriptionDailyResetEvent.
type SubscriptionDailyResetEvents []*SubscriptionDailyResetEvent
