// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptiondailyresetevent"
)

// SubscriptionDailyResetEventDelete is the builder for deleting a SubscriptionDailyResetEvent entity.
type SubscriptionDailyResetEventDelete struct {
	config
	hooks    []Hook
	mutation *SubscriptionDailyResetEventMutation
}

// Where appends a list predicates to the SubscriptionDailyResetEventDelete builder.
func (_d *SubscriptionDailyResetEventDelete) Where(ps ...predicate.SubscriptionDailyResetEvent) *SubscriptionDailyResetEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SubscriptionDailyResetEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionDailyResetEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SubscriptionDailyResetEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(subscriptiondailyresetevent.Table, sqlgraph.NewFieldSpec(subscriptiondailyresetevent.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SubscriptionDailyResetEventDeleteOne is the builder for deleting a single SubscriptionDailyResetEvent entity.
type SubscriptionDailyResetEventDeleteOne struct {
	_d *SubscriptionDailyResetEventDelete
}

// Where appends a list predicates to the SubscriptionDailyResetEventDelete builder.
func (_d *SubscriptionDailyResetEventDeleteOne) Where(ps ...predicate.SubscriptionDailyResetEvent) *SubscriptionDailyResetEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SubscriptionDailyResetEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subscriptiondailyresetevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SubscriptionDailyResetEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
