// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/subscriptiondailyresetevent"
)

// SubscriptionDailyResetEventCreate is the builder for creating a SubscriptionDailyResetEvent entity.
type SubscriptionDailyResetEventCreate struct {
	config
	mutation *SubscriptionDailyResetEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *SubscriptionDailyResetEventCreate) SetSubscriptionID(v int64) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SubscriptionDailyResetEventCreate) SetUserID(v int64) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *SubscriptionDailyResetEventCreate) SetGroupID(v int64) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *SubscriptionDailyResetEventCreate) SetSource(v string) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetOperationID sets the "operation_id" field.
func (_c *SubscriptionDailyResetEventCreate) SetOperationID(v string) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetOperationID(v)
	return _c
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_c *SubscriptionDailyResetEventCreate) SetRequestFingerprint(v string) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetRequestFingerprint(v)
	return _c
}

// SetBeforeVersion sets the "before_version" field.
func (_c *SubscriptionDailyResetEventCreate) SetBeforeVersion(v int64) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetBeforeVersion(v)
	return _c
}

// SetAfterVersion sets the "after_version" field.
func (_c *SubscriptionDailyResetEventCreate) SetAfterVersion(v int64) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetAfterVersion(v)
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *SubscriptionDailyResetEventCreate) SetTimezone(v string) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetCountDate sets the "count_date" field.
func (_c *SubscriptionDailyResetEventCreate) SetCountDate(v time.Time) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetCountDate(v)
	return _c
}

// SetDaySequence sets the "day_sequence" field.
func (_c *SubscriptionDailyResetEventCreate) SetDaySequence(v int) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetDaySequence(v)
	return _c
}

// SetBeforeDailyUsageUsd sets the "before_daily_usage_usd" field.
func (_c *SubscriptionDailyResetEventCreate) SetBeforeDailyUsageUsd(v float64) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetBeforeDailyUsageUsd(v)
	return _c
}

// SetAfterDailyUsageUsd sets the "after_daily_usage_usd" field.
func (_c *SubscriptionDailyResetEventCreate) SetAfterDailyUsageUsd(v float64) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetAfterDailyUsageUsd(v)
	return _c
}

// SetNillableAfterDailyUsageUsd sets the "after_daily_usage_usd" field if the given value is not nil.
func (_c *SubscriptionDailyResetEventCreate) SetNillableAfterDailyUsageUsd(v *float64) *SubscriptionDailyResetEventCreate {
	if v != nil {
		_c.SetAfterDailyUsageUsd(*v)
	}
	return _c
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_c *SubscriptionDailyResetEventCreate) SetDailyLimitUsd(v float64) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetDailyLimitUsd(v)
	return _c
}

// SetBeforeExpiresAt sets the "before_expires_at" field.
func (_c *SubscriptionDailyResetEventCreate) SetBeforeExpiresAt(v time.Time) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetBeforeExpiresAt(v)
	return _c
}

// SetAfterExpiresAt sets the "after_expires_at" field.
func (_c *SubscriptionDailyResetEventCreate) SetAfterExpiresAt(v time.Time) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetAfterExpiresAt(v)
	return _c
}

// SetDeductedSeconds sets the "deducted_seconds" field.
func (_c *SubscriptionDailyResetEventCreate) SetDeductedSeconds(v int) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetDeductedSeconds(v)
	return _c
}

// SetNillableDeductedSeconds sets the "deducted_seconds" field if the given value is not nil.
func (_c *SubscriptionDailyResetEventCreate) SetNillableDeductedSeconds(v *int) *SubscriptionDailyResetEventCreate {
	if v != nil {
		_c.SetDeductedSeconds(*v)
	}
	return _c
}

// SetDecidedAt sets the "decided_at" field.
func (_c *SubscriptionDailyResetEventCreate) SetDecidedAt(v time.Time) *SubscriptionDailyResetEventCreate {
	_c.mutation.SetDecidedAt(v)
	return _c
}

// Mutation returns the SubscriptionDailyResetEventMutation object of the builder.
func (_c *SubscriptionDailyResetEventCreate) Mutation() *SubscriptionDailyResetEventMutation {
	return _c.mutation
}

// Save creates the SubscriptionDailyResetEvent in the database.
func (_c *SubscriptionDailyResetEventCreate) Save(ctx context.Context) (*SubscriptionDailyResetEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionDailyResetEventCreate) SaveX(ctx context.Context) *SubscriptionDailyResetEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionDailyResetEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionDailyResetEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionDailyResetEventCreate) defaults() {
	if _, ok := _c.mutation.AfterDailyUsageUsd(); !ok {
		v := subscriptiondailyresetevent.DefaultAfterDailyUsageUsd
		_c.mutation.SetAfterDailyUsageUsd(v)
	}
	if _, ok := _c.mutation.DeductedSeconds(); !ok {
		v := subscriptiondailyresetevent.DefaultDeductedSeconds
		_c.mutation.SetDeductedSeconds(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionDailyResetEventCreate) check() error {
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.subscription_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.group_id"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := subscriptiondailyresetevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OperationID(); !ok {
		return &ValidationError{Name: "operation_id", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.operation_id"`)}
	}
	if v, ok := _c.mutation.OperationID(); ok {
		if err := subscriptiondailyresetevent.OperationIDValidator(v); err != nil {
			return &ValidationError{Name: "operation_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.operation_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestFingerprint(); !ok {
		return &ValidationError{Name: "request_fingerprint", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.request_fingerprint"`)}
	}
	if v, ok := _c.mutation.RequestFingerprint(); ok {
		if err := subscriptiondailyresetevent.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.request_fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BeforeVersion(); !ok {
		return &ValidationError{Name: "before_version", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.before_version"`)}
	}
	if v, ok := _c.mutation.BeforeVersion(); ok {
		if err := subscriptiondailyresetevent.BeforeVersionValidator(v); err != nil {
			return &ValidationError{Name: "before_version", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.before_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AfterVersion(); !ok {
		return &ValidationError{Name: "after_version", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.after_version"`)}
	}
	if v, ok := _c.mutation.AfterVersion(); ok {
		if err := subscriptiondailyresetevent.AfterVersionValidator(v); err != nil {
			return &ValidationError{Name: "after_version", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.after_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.timezone"`)}
	}
	if v, ok := _c.mutation.Timezone(); ok {
		if err := subscriptiondailyresetevent.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.timezone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CountDate(); !ok {
		return &ValidationError{Name: "count_date", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.count_date"`)}
	}
	if _, ok := _c.mutation.DaySequence(); !ok {
		return &ValidationError{Name: "day_sequence", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.day_sequence"`)}
	}
	if v, ok := _c.mutation.DaySequence(); ok {
		if err := subscriptiondailyresetevent.DaySequenceValidator(v); err != nil {
			return &ValidationError{Name: "day_sequence", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.day_sequence": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BeforeDailyUsageUsd(); !ok {
		return &ValidationError{Name: "before_daily_usage_usd", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.before_daily_usage_usd"`)}
	}
	if _, ok := _c.mutation.AfterDailyUsageUsd(); !ok {
		return &ValidationError{Name: "after_daily_usage_usd", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.after_daily_usage_usd"`)}
	}
	if _, ok := _c.mutation.DailyLimitUsd(); !ok {
		return &ValidationError{Name: "daily_limit_usd", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.daily_limit_usd"`)}
	}
	if _, ok := _c.mutation.BeforeExpiresAt(); !ok {
		return &ValidationError{Name: "before_expires_at", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.before_expires_at"`)}
	}
	if _, ok := _c.mutation.AfterExpiresAt(); !ok {
		return &ValidationError{Name: "after_expires_at", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.after_expires_at"`)}
	}
	if _, ok := _c.mutation.DeductedSeconds(); !ok {
		return &ValidationError{Name: "deducted_seconds", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.deducted_seconds"`)}
	}
	if _, ok := _c.mutation.DecidedAt(); !ok {
		return &ValidationError{Name: "decided_at", err: errors.New(`ent: missing required field "SubscriptionDailyResetEvent.decided_at"`)}
	}
	return nil
}

func (_c *SubscriptionDailyResetEventCreate) sqlSave(ctx context.Context) (*SubscriptionDailyResetEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionDailyResetEventCreate) createSpec() (*SubscriptionDailyResetEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionDailyResetEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptiondailyresetevent.Table, sqlgraph.NewFieldSpec(subscriptiondailyresetevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldSubscriptionID, field.TypeInt64, value)
		_node.SubscriptionID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.OperationID(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldOperationID, field.TypeString, value)
		_node.OperationID = value
	}
	if value, ok := _c.mutation.RequestFingerprint(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldRequestFingerprint, field.TypeString, value)
		_node.RequestFingerprint = value
	}
	if value, ok := _c.mutation.BeforeVersion(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldBeforeVersion, field.TypeInt64, value)
		_node.BeforeVersion = value
	}
	if value, ok := _c.mutation.AfterVersion(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldAfterVersion, field.TypeInt64, value)
		_node.AfterVersion = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.CountDate(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldCountDate, field.TypeTime, value)
		_node.CountDate = value
	}
	if value, ok := _c.mutation.DaySequence(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldDaySequence, field.TypeInt, value)
		_node.DaySequence = value
	}
	if value, ok := _c.mutation.BeforeDailyUsageUsd(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldBeforeDailyUsageUsd, field.TypeFloat64, value)
		_node.BeforeDailyUsageUsd = value
	}
	if value, ok := _c.mutation.AfterDailyUsageUsd(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldAfterDailyUsageUsd, field.TypeFloat64, value)
		_node.AfterDailyUsageUsd = value
	}
	if value, ok := _c.mutation.DailyLimitUsd(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldDailyLimitUsd, field.TypeFloat64, value)
		_node.DailyLimitUsd = value
	}
	if value, ok := _c.mutation.BeforeExpiresAt(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldBeforeExpiresAt, field.TypeTime, value)
		_node.BeforeExpiresAt = value
	}
	if value, ok := _c.mutation.AfterExpiresAt(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldAfterExpiresAt, field.TypeTime, value)
		_node.AfterExpiresAt = value
	}
	if value, ok := _c.mutation.DeductedSeconds(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldDeductedSeconds, field.TypeInt, value)
		_node.DeductedSeconds = value
	}
	if value, ok := _c.mutation.DecidedAt(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldDecidedAt, field.TypeTime, value)
		_node.DecidedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionDailyResetEvent.Create().
//		SetSubscriptionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionDailyResetEventUpsert) {
//			SetSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionDailyResetEventCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionDailyResetEventUpsertOne {
	_c.conflict = opts
	return &SubscriptionDailyResetEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionDailyResetEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionDailyResetEventCreate) OnConflictColumns(columns ...string) *SubscriptionDailyResetEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionDailyResetEventUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionDailyResetEventUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionDailyResetEvent node.
	SubscriptionDailyResetEventUpsertOne struct {
		create *SubscriptionDailyResetEventCreate
	}

	// SubscriptionDailyResetEventUpsert is the "OnConflict" setter.
	SubscriptionDailyResetEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionDailyResetEventUpsert) SetSubscriptionID(v int64) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateSubscriptionID() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldSubscriptionID)
	return u
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *SubscriptionDailyResetEventUpsert) AddSubscriptionID(v int64) *SubscriptionDailyResetEventUpsert {
	u.Add(subscriptiondailyresetevent.FieldSubscriptionID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionDailyResetEventUpsert) SetUserID(v int64) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateUserID() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *SubscriptionDailyResetEventUpsert) AddUserID(v int64) *SubscriptionDailyResetEventUpsert {
	u.Add(subscriptiondailyresetevent.FieldUserID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionDailyResetEventUpsert) SetGroupID(v int64) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateGroupID() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *SubscriptionDailyResetEventUpsert) AddGroupID(v int64) *SubscriptionDailyResetEventUpsert {
	u.Add(subscriptiondailyresetevent.FieldGroupID, v)
	return u
}

// SetSource sets the "source" field.
func (u *SubscriptionDailyResetEventUpsert) SetSource(v string) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateSource() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldSource)
	return u
}

// SetOperationID sets the "operation_id" field.
func (u *SubscriptionDailyResetEventUpsert) SetOperationID(v string) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldOperationID, v)
	return u
}

// UpdateOperationID sets the "operation_id" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateOperationID() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldOperationID)
	return u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *SubscriptionDailyResetEventUpsert) SetRequestFingerprint(v string) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldRequestFingerprint, v)
	return u
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateRequestFingerprint() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldRequestFingerprint)
	return u
}

// SetBeforeVersion sets the "before_version" field.
func (u *SubscriptionDailyResetEventUpsert) SetBeforeVersion(v int64) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldBeforeVersion, v)
	return u
}

// UpdateBeforeVersion sets the "before_version" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateBeforeVersion() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldBeforeVersion)
	return u
}

// AddBeforeVersion adds v to the "before_version" field.
func (u *SubscriptionDailyResetEventUpsert) AddBeforeVersion(v int64) *SubscriptionDailyResetEventUpsert {
	u.Add(subscriptiondailyresetevent.FieldBeforeVersion, v)
	return u
}

// SetAfterVersion sets the "after_version" field.
func (u *SubscriptionDailyResetEventUpsert) SetAfterVersion(v int64) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldAfterVersion, v)
	return u
}

// UpdateAfterVersion sets the "after_version" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateAfterVersion() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldAfterVersion)
	return u
}

// AddAfterVersion adds v to the "after_version" field.
func (u *SubscriptionDailyResetEventUpsert) AddAfterVersion(v int64) *SubscriptionDailyResetEventUpsert {
	u.Add(subscriptiondailyresetevent.FieldAfterVersion, v)
	return u
}

// SetTimezone sets the "timezone" field.
func (u *SubscriptionDailyResetEventUpsert) SetTimezone(v string) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldTimezone, v)
	return u
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateTimezone() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldTimezone)
	return u
}

// SetCountDate sets the "count_date" field.
func (u *SubscriptionDailyResetEventUpsert) SetCountDate(v time.Time) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldCountDate, v)
	return u
}

// UpdateCountDate sets the "count_date" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateCountDate() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldCountDate)
	return u
}

// SetDaySequence sets the "day_sequence" field.
func (u *SubscriptionDailyResetEventUpsert) SetDaySequence(v int) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldDaySequence, v)
	return u
}

// UpdateDaySequence sets the "day_sequence" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateDaySequence() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldDaySequence)
	return u
}

// AddDaySequence adds v to the "day_sequence" field.
func (u *SubscriptionDailyResetEventUpsert) AddDaySequence(v int) *SubscriptionDailyResetEventUpsert {
	u.Add(subscriptiondailyresetevent.FieldDaySequence, v)
	return u
}

// SetBeforeDailyUsageUsd sets the "before_daily_usage_usd" field.
func (u *SubscriptionDailyResetEventUpsert) SetBeforeDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldBeforeDailyUsageUsd, v)
	return u
}

// UpdateBeforeDailyUsageUsd sets the "before_daily_usage_usd" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateBeforeDailyUsageUsd() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldBeforeDailyUsageUsd)
	return u
}

// AddBeforeDailyUsageUsd adds v to the "before_daily_usage_usd" field.
func (u *SubscriptionDailyResetEventUpsert) AddBeforeDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpsert {
	u.Add(subscriptiondailyresetevent.FieldBeforeDailyUsageUsd, v)
	return u
}

// SetAfterDailyUsageUsd sets the "after_daily_usage_usd" field.
func (u *SubscriptionDailyResetEventUpsert) SetAfterDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldAfterDailyUsageUsd, v)
	return u
}

// UpdateAfterDailyUsageUsd sets the "after_daily_usage_usd" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateAfterDailyUsageUsd() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldAfterDailyUsageUsd)
	return u
}

// AddAfterDailyUsageUsd adds v to the "after_daily_usage_usd" field.
func (u *SubscriptionDailyResetEventUpsert) AddAfterDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpsert {
	u.Add(subscriptiondailyresetevent.FieldAfterDailyUsageUsd, v)
	return u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *SubscriptionDailyResetEventUpsert) SetDailyLimitUsd(v float64) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldDailyLimitUsd, v)
	return u
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateDailyLimitUsd() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldDailyLimitUsd)
	return u
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *SubscriptionDailyResetEventUpsert) AddDailyLimitUsd(v float64) *SubscriptionDailyResetEventUpsert {
	u.Add(subscriptiondailyresetevent.FieldDailyLimitUsd, v)
	return u
}

// SetBeforeExpiresAt sets the "before_expires_at" field.
func (u *SubscriptionDailyResetEventUpsert) SetBeforeExpiresAt(v time.Time) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldBeforeExpiresAt, v)
	return u
}

// UpdateBeforeExpiresAt sets the "before_expires_at" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateBeforeExpiresAt() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldBeforeExpiresAt)
	return u
}

// SetAfterExpiresAt sets the "after_expires_at" field.
func (u *SubscriptionDailyResetEventUpsert) SetAfterExpiresAt(v time.Time) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldAfterExpiresAt, v)
	return u
}

// UpdateAfterExpiresAt sets the "after_expires_at" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateAfterExpiresAt() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldAfterExpiresAt)
	return u
}

// SetDeductedSeconds sets the "deducted_seconds" field.
func (u *SubscriptionDailyResetEventUpsert) SetDeductedSeconds(v int) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldDeductedSeconds, v)
	return u
}

// UpdateDeductedSeconds sets the "deducted_seconds" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateDeductedSeconds() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldDeductedSeconds)
	return u
}

// AddDeductedSeconds adds v to the "deducted_seconds" field.
func (u *SubscriptionDailyResetEventUpsert) AddDeductedSeconds(v int) *SubscriptionDailyResetEventUpsert {
	u.Add(subscriptiondailyresetevent.FieldDeductedSeconds, v)
	return u
}

// SetDecidedAt sets the "decided_at" field.
func (u *SubscriptionDailyResetEventUpsert) SetDecidedAt(v time.Time) *SubscriptionDailyResetEventUpsert {
	u.Set(subscriptiondailyresetevent.FieldDecidedAt, v)
	return u
}

// UpdateDecidedAt sets the "decided_at" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsert) UpdateDecidedAt() *SubscriptionDailyResetEventUpsert {
	u.SetExcluded(subscriptiondailyresetevent.FieldDecidedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionDailyResetEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionDailyResetEventUpsertOne) UpdateNewValues() *SubscriptionDailyResetEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionDailyResetEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionDailyResetEventUpsertOne) Ignore() *SubscriptionDailyResetEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionDailyResetEventUpsertOne) DoNothing() *SubscriptionDailyResetEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionDailyResetEventCreate.OnConflict
// documentation for more info.
func (u *SubscriptionDailyResetEventUpsertOne) Update(set func(*SubscriptionDailyResetEventUpsert)) *SubscriptionDailyResetEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionDailyResetEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetSubscriptionID(v int64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *SubscriptionDailyResetEventUpsertOne) AddSubscriptionID(v int64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateSubscriptionID() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetUserID(v int64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SubscriptionDailyResetEventUpsertOne) AddUserID(v int64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateUserID() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetGroupID(v int64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SubscriptionDailyResetEventUpsertOne) AddGroupID(v int64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateGroupID() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateGroupID()
	})
}

// SetSource sets the "source" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetSource(v string) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateSource() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateSource()
	})
}

// SetOperationID sets the "operation_id" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetOperationID(v string) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetOperationID(v)
	})
}

// UpdateOperationID sets the "operation_id" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateOperationID() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateOperationID()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetRequestFingerprint(v string) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateRequestFingerprint() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// SetBeforeVersion sets the "before_version" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetBeforeVersion(v int64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetBeforeVersion(v)
	})
}

// AddBeforeVersion adds v to the "before_version" field.
func (u *SubscriptionDailyResetEventUpsertOne) AddBeforeVersion(v int64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddBeforeVersion(v)
	})
}

// UpdateBeforeVersion sets the "before_version" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateBeforeVersion() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateBeforeVersion()
	})
}

// SetAfterVersion sets the "after_version" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetAfterVersion(v int64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetAfterVersion(v)
	})
}

// AddAfterVersion adds v to the "after_version" field.
func (u *SubscriptionDailyResetEventUpsertOne) AddAfterVersion(v int64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddAfterVersion(v)
	})
}

// UpdateAfterVersion sets the "after_version" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateAfterVersion() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateAfterVersion()
	})
}

// SetTimezone sets the "timezone" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetTimezone(v string) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateTimezone() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateTimezone()
	})
}

// SetCountDate sets the "count_date" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetCountDate(v time.Time) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetCountDate(v)
	})
}

// UpdateCountDate sets the "count_date" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateCountDate() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateCountDate()
	})
}

// SetDaySequence sets the "day_sequence" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetDaySequence(v int) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetDaySequence(v)
	})
}

// AddDaySequence adds v to the "day_sequence" field.
func (u *SubscriptionDailyResetEventUpsertOne) AddDaySequence(v int) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddDaySequence(v)
	})
}

// UpdateDaySequence sets the "day_sequence" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateDaySequence() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateDaySequence()
	})
}

// SetBeforeDailyUsageUsd sets the "before_daily_usage_usd" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetBeforeDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetBeforeDailyUsageUsd(v)
	})
}

// AddBeforeDailyUsageUsd adds v to the "before_daily_usage_usd" field.
func (u *SubscriptionDailyResetEventUpsertOne) AddBeforeDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddBeforeDailyUsageUsd(v)
	})
}

// UpdateBeforeDailyUsageUsd sets the "before_daily_usage_usd" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateBeforeDailyUsageUsd() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateBeforeDailyUsageUsd()
	})
}

// SetAfterDailyUsageUsd sets the "after_daily_usage_usd" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetAfterDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetAfterDailyUsageUsd(v)
	})
}

// AddAfterDailyUsageUsd adds v to the "after_daily_usage_usd" field.
func (u *SubscriptionDailyResetEventUpsertOne) AddAfterDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddAfterDailyUsageUsd(v)
	})
}

// UpdateAfterDailyUsageUsd sets the "after_daily_usage_usd" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateAfterDailyUsageUsd() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateAfterDailyUsageUsd()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetDailyLimitUsd(v float64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *SubscriptionDailyResetEventUpsertOne) AddDailyLimitUsd(v float64) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateDailyLimitUsd() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// SetBeforeExpiresAt sets the "before_expires_at" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetBeforeExpiresAt(v time.Time) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetBeforeExpiresAt(v)
	})
}

// UpdateBeforeExpiresAt sets the "before_expires_at" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateBeforeExpiresAt() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateBeforeExpiresAt()
	})
}

// SetAfterExpiresAt sets the "after_expires_at" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetAfterExpiresAt(v time.Time) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetAfterExpiresAt(v)
	})
}

// UpdateAfterExpiresAt sets the "after_expires_at" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateAfterExpiresAt() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateAfterExpiresAt()
	})
}

// SetDeductedSeconds sets the "deducted_seconds" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetDeductedSeconds(v int) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetDeductedSeconds(v)
	})
}

// AddDeductedSeconds adds v to the "deducted_seconds" field.
func (u *SubscriptionDailyResetEventUpsertOne) AddDeductedSeconds(v int) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddDeductedSeconds(v)
	})
}

// UpdateDeductedSeconds sets the "deducted_seconds" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateDeductedSeconds() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateDeductedSeconds()
	})
}

// SetDecidedAt sets the "decided_at" field.
func (u *SubscriptionDailyResetEventUpsertOne) SetDecidedAt(v time.Time) *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetDecidedAt(v)
	})
}

// UpdateDecidedAt sets the "decided_at" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertOne) UpdateDecidedAt() *SubscriptionDailyResetEventUpsertOne {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateDecidedAt()
	})
}

// Exec executes the query.
func (u *SubscriptionDailyResetEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionDailyResetEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionDailyResetEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionDailyResetEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionDailyResetEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionDailyResetEventCreateBulk is the builder for creating many SubscriptionDailyResetEvent entities in bulk.
type SubscriptionDailyResetEventCreateBulk struct {
	config
	err      error
	builders []*SubscriptionDailyResetEventCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionDailyResetEvent entities in the database.
func (_c *SubscriptionDailyResetEventCreateBulk) Save(ctx context.Context) ([]*SubscriptionDailyResetEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionDailyResetEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionDailyResetEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionDailyResetEventCreateBulk) SaveX(ctx context.Context) []*SubscriptionDailyResetEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionDailyResetEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionDailyResetEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionDailyResetEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionDailyResetEventUpsert) {
//			SetSubscriptionID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionDailyResetEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionDailyResetEventUpsertBulk {
	_c.conflict = opts
	return &SubscriptionDailyResetEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionDailyResetEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionDailyResetEventCreateBulk) OnConflictColumns(columns ...string) *SubscriptionDailyResetEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionDailyResetEventUpsertBulk{
		create: _c,
	}
}

// SubscriptionDailyResetEventUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionDailyResetEvent nodes.
type SubscriptionDailyResetEventUpsertBulk struct {
	create *SubscriptionDailyResetEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionDailyResetEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateNewValues() *SubscriptionDailyResetEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionDailyResetEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionDailyResetEventUpsertBulk) Ignore() *SubscriptionDailyResetEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionDailyResetEventUpsertBulk) DoNothing() *SubscriptionDailyResetEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionDailyResetEventCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionDailyResetEventUpsertBulk) Update(set func(*SubscriptionDailyResetEventUpsert)) *SubscriptionDailyResetEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionDailyResetEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetSubscriptionID(v int64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetSubscriptionID(v)
	})
}

// AddSubscriptionID adds v to the "subscription_id" field.
func (u *SubscriptionDailyResetEventUpsertBulk) AddSubscriptionID(v int64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateSubscriptionID() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetUserID(v int64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SubscriptionDailyResetEventUpsertBulk) AddUserID(v int64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateUserID() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetGroupID(v int64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *SubscriptionDailyResetEventUpsertBulk) AddGroupID(v int64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateGroupID() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateGroupID()
	})
}

// SetSource sets the "source" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetSource(v string) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateSource() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateSource()
	})
}

// SetOperationID sets the "operation_id" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetOperationID(v string) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetOperationID(v)
	})
}

// UpdateOperationID sets the "operation_id" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateOperationID() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateOperationID()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetRequestFingerprint(v string) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateRequestFingerprint() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// SetBeforeVersion sets the "before_version" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetBeforeVersion(v int64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetBeforeVersion(v)
	})
}

// AddBeforeVersion adds v to the "before_version" field.
func (u *SubscriptionDailyResetEventUpsertBulk) AddBeforeVersion(v int64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddBeforeVersion(v)
	})
}

// UpdateBeforeVersion sets the "before_version" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateBeforeVersion() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateBeforeVersion()
	})
}

// SetAfterVersion sets the "after_version" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetAfterVersion(v int64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetAfterVersion(v)
	})
}

// AddAfterVersion adds v to the "after_version" field.
func (u *SubscriptionDailyResetEventUpsertBulk) AddAfterVersion(v int64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddAfterVersion(v)
	})
}

// UpdateAfterVersion sets the "after_version" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateAfterVersion() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateAfterVersion()
	})
}

// SetTimezone sets the "timezone" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetTimezone(v string) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateTimezone() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateTimezone()
	})
}

// SetCountDate sets the "count_date" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetCountDate(v time.Time) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetCountDate(v)
	})
}

// UpdateCountDate sets the "count_date" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateCountDate() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateCountDate()
	})
}

// SetDaySequence sets the "day_sequence" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetDaySequence(v int) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetDaySequence(v)
	})
}

// AddDaySequence adds v to the "day_sequence" field.
func (u *SubscriptionDailyResetEventUpsertBulk) AddDaySequence(v int) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddDaySequence(v)
	})
}

// UpdateDaySequence sets the "day_sequence" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateDaySequence() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateDaySequence()
	})
}

// SetBeforeDailyUsageUsd sets the "before_daily_usage_usd" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetBeforeDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetBeforeDailyUsageUsd(v)
	})
}

// AddBeforeDailyUsageUsd adds v to the "before_daily_usage_usd" field.
func (u *SubscriptionDailyResetEventUpsertBulk) AddBeforeDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddBeforeDailyUsageUsd(v)
	})
}

// UpdateBeforeDailyUsageUsd sets the "before_daily_usage_usd" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateBeforeDailyUsageUsd() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateBeforeDailyUsageUsd()
	})
}

// SetAfterDailyUsageUsd sets the "after_daily_usage_usd" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetAfterDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetAfterDailyUsageUsd(v)
	})
}

// AddAfterDailyUsageUsd adds v to the "after_daily_usage_usd" field.
func (u *SubscriptionDailyResetEventUpsertBulk) AddAfterDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddAfterDailyUsageUsd(v)
	})
}

// UpdateAfterDailyUsageUsd sets the "after_daily_usage_usd" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateAfterDailyUsageUsd() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateAfterDailyUsageUsd()
	})
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetDailyLimitUsd(v float64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetDailyLimitUsd(v)
	})
}

// AddDailyLimitUsd adds v to the "daily_limit_usd" field.
func (u *SubscriptionDailyResetEventUpsertBulk) AddDailyLimitUsd(v float64) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddDailyLimitUsd(v)
	})
}

// UpdateDailyLimitUsd sets the "daily_limit_usd" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateDailyLimitUsd() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateDailyLimitUsd()
	})
}

// SetBeforeExpiresAt sets the "before_expires_at" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetBeforeExpiresAt(v time.Time) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetBeforeExpiresAt(v)
	})
}

// UpdateBeforeExpiresAt sets the "before_expires_at" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateBeforeExpiresAt() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateBeforeExpiresAt()
	})
}

// SetAfterExpiresAt sets the "after_expires_at" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetAfterExpiresAt(v time.Time) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetAfterExpiresAt(v)
	})
}

// UpdateAfterExpiresAt sets the "after_expires_at" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateAfterExpiresAt() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateAfterExpiresAt()
	})
}

// SetDeductedSeconds sets the "deducted_seconds" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetDeductedSeconds(v int) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetDeductedSeconds(v)
	})
}

// AddDeductedSeconds adds v to the "deducted_seconds" field.
func (u *SubscriptionDailyResetEventUpsertBulk) AddDeductedSeconds(v int) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.AddDeductedSeconds(v)
	})
}

// UpdateDeductedSeconds sets the "deducted_seconds" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateDeductedSeconds() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateDeductedSeconds()
	})
}

// SetDecidedAt sets the "decided_at" field.
func (u *SubscriptionDailyResetEventUpsertBulk) SetDecidedAt(v time.Time) *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.SetDecidedAt(v)
	})
}

// UpdateDecidedAt sets the "decided_at" field to the value that was provided on create.
func (u *SubscriptionDailyResetEventUpsertBulk) UpdateDecidedAt() *SubscriptionDailyResetEventUpsertBulk {
	return u.Update(func(s *SubscriptionDailyResetEventUpsert) {
		s.UpdateDecidedAt()
	})
}

// Exec executes the query.
func (u *SubscriptionDailyResetEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionDailyResetEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionDailyResetEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionDailyResetEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
