// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptiondailyresetevent"
)

// SubscriptionDailyResetEventUpdate is the builder for updating SubscriptionDailyResetEvent entities.
type SubscriptionDailyResetEventUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionDailyResetEventMutation
}

// Where appends a list predicates to the SubscriptionDailyResetEventUpdate builder.
func (_u *SubscriptionDailyResetEventUpdate) Where(ps ...predicate.SubscriptionDailyResetEvent) *SubscriptionDailyResetEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionDailyResetEventUpdate) SetSubscriptionID(v int64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableSubscriptionID(v *int64) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *SubscriptionDailyResetEventUpdate) AddSubscriptionID(v int64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionDailyResetEventUpdate) SetUserID(v int64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableUserID(v *int64) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SubscriptionDailyResetEventUpdate) AddUserID(v int64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionDailyResetEventUpdate) SetGroupID(v int64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableGroupID(v *int64) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubscriptionDailyResetEventUpdate) AddGroupID(v int64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *SubscriptionDailyResetEventUpdate) SetSource(v string) *SubscriptionDailyResetEventUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableSource(v *string) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetOperationID sets the "operation_id" field.
func (_u *SubscriptionDailyResetEventUpdate) SetOperationID(v string) *SubscriptionDailyResetEventUpdate {
	_u.mutation.SetOperationID(v)
	return _u
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableOperationID(v *string) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetOperationID(*v)
	}
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *SubscriptionDailyResetEventUpdate) SetRequestFingerprint(v string) *SubscriptionDailyResetEventUpdate {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableRequestFingerprint(v *string) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// SetBeforeVersion sets the "before_version" field.
func (_u *SubscriptionDailyResetEventUpdate) SetBeforeVersion(v int64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.ResetBeforeVersion()
	_u.mutation.SetBeforeVersion(v)
	return _u
}

// SetNillableBeforeVersion sets the "before_version" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableBeforeVersion(v *int64) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetBeforeVersion(*v)
	}
	return _u
}

// AddBeforeVersion adds value to the "before_version" field.
func (_u *SubscriptionDailyResetEventUpdate) AddBeforeVersion(v int64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.AddBeforeVersion(v)
	return _u
}

// SetAfterVersion sets the "after_version" field.
func (_u *SubscriptionDailyResetEventUpdate) SetAfterVersion(v int64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.ResetAfterVersion()
	_u.mutation.SetAfterVersion(v)
	return _u
}

// SetNillableAfterVersion sets the "after_version" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableAfterVersion(v *int64) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetAfterVersion(*v)
	}
	return _u
}

// AddAfterVersion adds value to the "after_version" field.
func (_u *SubscriptionDailyResetEventUpdate) AddAfterVersion(v int64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.AddAfterVersion(v)
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *SubscriptionDailyResetEventUpdate) SetTimezone(v string) *SubscriptionDailyResetEventUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableTimezone(v *string) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetCountDate sets the "count_date" field.
func (_u *SubscriptionDailyResetEventUpdate) SetCountDate(v time.Time) *SubscriptionDailyResetEventUpdate {
	_u.mutation.SetCountDate(v)
	return _u
}

// SetNillableCountDate sets the "count_date" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableCountDate(v *time.Time) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetCountDate(*v)
	}
	return _u
}

// SetDaySequence sets the "day_sequence" field.
func (_u *SubscriptionDailyResetEventUpdate) SetDaySequence(v int) *SubscriptionDailyResetEventUpdate {
	_u.mutation.ResetDaySequence()
	_u.mutation.SetDaySequence(v)
	return _u
}

// SetNillableDaySequence sets the "day_sequence" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableDaySequence(v *int) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetDaySequence(*v)
	}
	return _u
}

// AddDaySequence adds value to the "day_sequence" field.
func (_u *SubscriptionDailyResetEventUpdate) AddDaySequence(v int) *SubscriptionDailyResetEventUpdate {
	_u.mutation.AddDaySequence(v)
	return _u
}

// SetBeforeDailyUsageUsd sets the "before_daily_usage_usd" field.
func (_u *SubscriptionDailyResetEventUpdate) SetBeforeDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.ResetBeforeDailyUsageUsd()
	_u.mutation.SetBeforeDailyUsageUsd(v)
	return _u
}

// SetNillableBeforeDailyUsageUsd sets the "before_daily_usage_usd" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableBeforeDailyUsageUsd(v *float64) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetBeforeDailyUsageUsd(*v)
	}
	return _u
}

// AddBeforeDailyUsageUsd adds value to the "before_daily_usage_usd" field.
func (_u *SubscriptionDailyResetEventUpdate) AddBeforeDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.AddBeforeDailyUsageUsd(v)
	return _u
}

// SetAfterDailyUsageUsd sets the "after_daily_usage_usd" field.
func (_u *SubscriptionDailyResetEventUpdate) SetAfterDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.ResetAfterDailyUsageUsd()
	_u.mutation.SetAfterDailyUsageUsd(v)
	return _u
}

// SetNillableAfterDailyUsageUsd sets the "after_daily_usage_usd" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableAfterDailyUsageUsd(v *float64) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetAfterDailyUsageUsd(*v)
	}
	return _u
}

// AddAfterDailyUsageUsd adds value to the "after_daily_usage_usd" field.
func (_u *SubscriptionDailyResetEventUpdate) AddAfterDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.AddAfterDailyUsageUsd(v)
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *SubscriptionDailyResetEventUpdate) SetDailyLimitUsd(v float64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableDailyLimitUsd(v *float64) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *SubscriptionDailyResetEventUpdate) AddDailyLimitUsd(v float64) *SubscriptionDailyResetEventUpdate {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// SetBeforeExpiresAt sets the "before_expires_at" field.
func (_u *SubscriptionDailyResetEventUpdate) SetBeforeExpiresAt(v time.Time) *SubscriptionDailyResetEventUpdate {
	_u.mutation.SetBeforeExpiresAt(v)
	return _u
}

// SetNillableBeforeExpiresAt sets the "before_expires_at" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableBeforeExpiresAt(v *time.Time) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetBeforeExpiresAt(*v)
	}
	return _u
}

// SetAfterExpiresAt sets the "after_expires_at" field.
func (_u *SubscriptionDailyResetEventUpdate) SetAfterExpiresAt(v time.Time) *SubscriptionDailyResetEventUpdate {
	_u.mutation.SetAfterExpiresAt(v)
	return _u
}

// SetNillableAfterExpiresAt sets the "after_expires_at" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableAfterExpiresAt(v *time.Time) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetAfterExpiresAt(*v)
	}
	return _u
}

// SetDeductedSeconds sets the "deducted_seconds" field.
func (_u *SubscriptionDailyResetEventUpdate) SetDeductedSeconds(v int) *SubscriptionDailyResetEventUpdate {
	_u.mutation.ResetDeductedSeconds()
	_u.mutation.SetDeductedSeconds(v)
	return _u
}

// SetNillableDeductedSeconds sets the "deducted_seconds" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableDeductedSeconds(v *int) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetDeductedSeconds(*v)
	}
	return _u
}

// AddDeductedSeconds adds value to the "deducted_seconds" field.
func (_u *SubscriptionDailyResetEventUpdate) AddDeductedSeconds(v int) *SubscriptionDailyResetEventUpdate {
	_u.mutation.AddDeductedSeconds(v)
	return _u
}

// SetDecidedAt sets the "decided_at" field.
func (_u *SubscriptionDailyResetEventUpdate) SetDecidedAt(v time.Time) *SubscriptionDailyResetEventUpdate {
	_u.mutation.SetDecidedAt(v)
	return _u
}

// SetNillableDecidedAt sets the "decided_at" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdate) SetNillableDecidedAt(v *time.Time) *SubscriptionDailyResetEventUpdate {
	if v != nil {
		_u.SetDecidedAt(*v)
	}
	return _u
}

// Mutation returns the SubscriptionDailyResetEventMutation object of the builder.
func (_u *SubscriptionDailyResetEventUpdate) Mutation() *SubscriptionDailyResetEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionDailyResetEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionDailyResetEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionDailyResetEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionDailyResetEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionDailyResetEventUpdate) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := subscriptiondailyresetevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperationID(); ok {
		if err := subscriptiondailyresetevent.OperationIDValidator(v); err != nil {
			return &ValidationError{Name: "operation_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.operation_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestFingerprint(); ok {
		if err := subscriptiondailyresetevent.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.request_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BeforeVersion(); ok {
		if err := subscriptiondailyresetevent.BeforeVersionValidator(v); err != nil {
			return &ValidationError{Name: "before_version", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.before_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AfterVersion(); ok {
		if err := subscriptiondailyresetevent.AfterVersionValidator(v); err != nil {
			return &ValidationError{Name: "after_version", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.after_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := subscriptiondailyresetevent.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DaySequence(); ok {
		if err := subscriptiondailyresetevent.DaySequenceValidator(v); err != nil {
			return &ValidationError{Name: "day_sequence", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.day_sequence": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionDailyResetEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptiondailyresetevent.Table, subscriptiondailyresetevent.Columns, sqlgraph.NewFieldSpec(subscriptiondailyresetevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperationID(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldOperationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldRequestFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.BeforeVersion(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldBeforeVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBeforeVersion(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldBeforeVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AfterVersion(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldAfterVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAfterVersion(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldAfterVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.CountDate(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldCountDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DaySequence(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldDaySequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDaySequence(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldDaySequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BeforeDailyUsageUsd(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldBeforeDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBeforeDailyUsageUsd(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldBeforeDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AfterDailyUsageUsd(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldAfterDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAfterDailyUsageUsd(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldAfterDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BeforeExpiresAt(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldBeforeExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AfterExpiresAt(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldAfterExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeductedSeconds(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldDeductedSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeductedSeconds(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldDeductedSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DecidedAt(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldDecidedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptiondailyresetevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionDailyResetEventUpdateOne is the builder for updating a single SubscriptionDailyResetEvent entity.
type SubscriptionDailyResetEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionDailyResetEventMutation
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetSubscriptionID(v int64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.ResetSubscriptionID()
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableSubscriptionID(v *int64) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// AddSubscriptionID adds value to the "subscription_id" field.
func (_u *SubscriptionDailyResetEventUpdateOne) AddSubscriptionID(v int64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.AddSubscriptionID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetUserID(v int64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableUserID(v *int64) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SubscriptionDailyResetEventUpdateOne) AddUserID(v int64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetGroupID(v int64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableGroupID(v *int64) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SubscriptionDailyResetEventUpdateOne) AddGroupID(v int64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetSource(v string) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableSource(v *string) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetOperationID sets the "operation_id" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetOperationID(v string) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.SetOperationID(v)
	return _u
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableOperationID(v *string) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetOperationID(*v)
	}
	return _u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetRequestFingerprint(v string) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.SetRequestFingerprint(v)
	return _u
}

// SetNillableRequestFingerprint sets the "request_fingerprint" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableRequestFingerprint(v *string) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetRequestFingerprint(*v)
	}
	return _u
}

// SetBeforeVersion sets the "before_version" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetBeforeVersion(v int64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.ResetBeforeVersion()
	_u.mutation.SetBeforeVersion(v)
	return _u
}

// SetNillableBeforeVersion sets the "before_version" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableBeforeVersion(v *int64) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetBeforeVersion(*v)
	}
	return _u
}

// AddBeforeVersion adds value to the "before_version" field.
func (_u *SubscriptionDailyResetEventUpdateOne) AddBeforeVersion(v int64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.AddBeforeVersion(v)
	return _u
}

// SetAfterVersion sets the "after_version" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetAfterVersion(v int64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.ResetAfterVersion()
	_u.mutation.SetAfterVersion(v)
	return _u
}

// SetNillableAfterVersion sets the "after_version" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableAfterVersion(v *int64) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetAfterVersion(*v)
	}
	return _u
}

// AddAfterVersion adds value to the "after_version" field.
func (_u *SubscriptionDailyResetEventUpdateOne) AddAfterVersion(v int64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.AddAfterVersion(v)
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetTimezone(v string) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableTimezone(v *string) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetCountDate sets the "count_date" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetCountDate(v time.Time) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.SetCountDate(v)
	return _u
}

// SetNillableCountDate sets the "count_date" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableCountDate(v *time.Time) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetCountDate(*v)
	}
	return _u
}

// SetDaySequence sets the "day_sequence" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetDaySequence(v int) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.ResetDaySequence()
	_u.mutation.SetDaySequence(v)
	return _u
}

// SetNillableDaySequence sets the "day_sequence" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableDaySequence(v *int) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetDaySequence(*v)
	}
	return _u
}

// AddDaySequence adds value to the "day_sequence" field.
func (_u *SubscriptionDailyResetEventUpdateOne) AddDaySequence(v int) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.AddDaySequence(v)
	return _u
}

// SetBeforeDailyUsageUsd sets the "before_daily_usage_usd" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetBeforeDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.ResetBeforeDailyUsageUsd()
	_u.mutation.SetBeforeDailyUsageUsd(v)
	return _u
}

// SetNillableBeforeDailyUsageUsd sets the "before_daily_usage_usd" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableBeforeDailyUsageUsd(v *float64) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetBeforeDailyUsageUsd(*v)
	}
	return _u
}

// AddBeforeDailyUsageUsd adds value to the "before_daily_usage_usd" field.
func (_u *SubscriptionDailyResetEventUpdateOne) AddBeforeDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.AddBeforeDailyUsageUsd(v)
	return _u
}

// SetAfterDailyUsageUsd sets the "after_daily_usage_usd" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetAfterDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.ResetAfterDailyUsageUsd()
	_u.mutation.SetAfterDailyUsageUsd(v)
	return _u
}

// SetNillableAfterDailyUsageUsd sets the "after_daily_usage_usd" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableAfterDailyUsageUsd(v *float64) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetAfterDailyUsageUsd(*v)
	}
	return _u
}

// AddAfterDailyUsageUsd adds value to the "after_daily_usage_usd" field.
func (_u *SubscriptionDailyResetEventUpdateOne) AddAfterDailyUsageUsd(v float64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.AddAfterDailyUsageUsd(v)
	return _u
}

// SetDailyLimitUsd sets the "daily_limit_usd" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetDailyLimitUsd(v float64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.ResetDailyLimitUsd()
	_u.mutation.SetDailyLimitUsd(v)
	return _u
}

// SetNillableDailyLimitUsd sets the "daily_limit_usd" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableDailyLimitUsd(v *float64) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetDailyLimitUsd(*v)
	}
	return _u
}

// AddDailyLimitUsd adds value to the "daily_limit_usd" field.
func (_u *SubscriptionDailyResetEventUpdateOne) AddDailyLimitUsd(v float64) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.AddDailyLimitUsd(v)
	return _u
}

// SetBeforeExpiresAt sets the "before_expires_at" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetBeforeExpiresAt(v time.Time) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.SetBeforeExpiresAt(v)
	return _u
}

// SetNillableBeforeExpiresAt sets the "before_expires_at" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableBeforeExpiresAt(v *time.Time) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetBeforeExpiresAt(*v)
	}
	return _u
}

// SetAfterExpiresAt sets the "after_expires_at" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetAfterExpiresAt(v time.Time) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.SetAfterExpiresAt(v)
	return _u
}

// SetNillableAfterExpiresAt sets the "after_expires_at" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableAfterExpiresAt(v *time.Time) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetAfterExpiresAt(*v)
	}
	return _u
}

// SetDeductedSeconds sets the "deducted_seconds" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetDeductedSeconds(v int) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.ResetDeductedSeconds()
	_u.mutation.SetDeductedSeconds(v)
	return _u
}

// SetNillableDeductedSeconds sets the "deducted_seconds" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableDeductedSeconds(v *int) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetDeductedSeconds(*v)
	}
	return _u
}

// AddDeductedSeconds adds value to the "deducted_seconds" field.
func (_u *SubscriptionDailyResetEventUpdateOne) AddDeductedSeconds(v int) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.AddDeductedSeconds(v)
	return _u
}

// SetDecidedAt sets the "decided_at" field.
func (_u *SubscriptionDailyResetEventUpdateOne) SetDecidedAt(v time.Time) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.SetDecidedAt(v)
	return _u
}

// SetNillableDecidedAt sets the "decided_at" field if the given value is not nil.
func (_u *SubscriptionDailyResetEventUpdateOne) SetNillableDecidedAt(v *time.Time) *SubscriptionDailyResetEventUpdateOne {
	if v != nil {
		_u.SetDecidedAt(*v)
	}
	return _u
}

// Mutation returns the SubscriptionDailyResetEventMutation object of the builder.
func (_u *SubscriptionDailyResetEventUpdateOne) Mutation() *SubscriptionDailyResetEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionDailyResetEventUpdate builder.
func (_u *SubscriptionDailyResetEventUpdateOne) Where(ps ...predicate.SubscriptionDailyResetEvent) *SubscriptionDailyResetEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionDailyResetEventUpdateOne) Select(field string, fields ...string) *SubscriptionDailyResetEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionDailyResetEvent entity.
func (_u *SubscriptionDailyResetEventUpdateOne) Save(ctx context.Context) (*SubscriptionDailyResetEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionDailyResetEventUpdateOne) SaveX(ctx context.Context) *SubscriptionDailyResetEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionDailyResetEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionDailyResetEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionDailyResetEventUpdateOne) check() error {
	if v, ok := _u.mutation.Source(); ok {
		if err := subscriptiondailyresetevent.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OperationID(); ok {
		if err := subscriptiondailyresetevent.OperationIDValidator(v); err != nil {
			return &ValidationError{Name: "operation_id", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.operation_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestFingerprint(); ok {
		if err := subscriptiondailyresetevent.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.request_fingerprint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BeforeVersion(); ok {
		if err := subscriptiondailyresetevent.BeforeVersionValidator(v); err != nil {
			return &ValidationError{Name: "before_version", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.before_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AfterVersion(); ok {
		if err := subscriptiondailyresetevent.AfterVersionValidator(v); err != nil {
			return &ValidationError{Name: "after_version", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.after_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := subscriptiondailyresetevent.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DaySequence(); ok {
		if err := subscriptiondailyresetevent.DaySequenceValidator(v); err != nil {
			return &ValidationError{Name: "day_sequence", err: fmt.Errorf(`ent: validator failed for field "SubscriptionDailyResetEvent.day_sequence": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionDailyResetEventUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionDailyResetEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptiondailyresetevent.Table, subscriptiondailyresetevent.Columns, sqlgraph.NewFieldSpec(subscriptiondailyresetevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionDailyResetEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptiondailyresetevent.FieldID)
		for _, f := range fields {
			if !subscriptiondailyresetevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptiondailyresetevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SubscriptionID(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionID(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldSubscriptionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.OperationID(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldOperationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestFingerprint(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldRequestFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.BeforeVersion(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldBeforeVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBeforeVersion(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldBeforeVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AfterVersion(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldAfterVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAfterVersion(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldAfterVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.CountDate(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldCountDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DaySequence(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldDaySequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDaySequence(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldDaySequence, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BeforeDailyUsageUsd(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldBeforeDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBeforeDailyUsageUsd(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldBeforeDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AfterDailyUsageUsd(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldAfterDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAfterDailyUsageUsd(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldAfterDailyUsageUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DailyLimitUsd(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLimitUsd(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldDailyLimitUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BeforeExpiresAt(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldBeforeExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AfterExpiresAt(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldAfterExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeductedSeconds(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldDeductedSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeductedSeconds(); ok {
		_spec.AddField(subscriptiondailyresetevent.FieldDeductedSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DecidedAt(); ok {
		_spec.SetField(subscriptiondailyresetevent.FieldDecidedAt, field.TypeTime, value)
	}
	_node = &SubscriptionDailyResetEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptiondailyresetevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
