export default {
  welfare: {
    recovering: 'Checking your previous operation…', pendingHint: 'Your previous result is unresolved. Retrying continues the same operation without duplicate charges.', pendingDraw: 'Unconfirmed draw', retryDraw: 'Retry previous draw', pendingRedemption: 'Unconfirmed redemption: {amount}', checkResult: 'Check operation result',
    title: 'Welfare center', subtitle: 'A little every day. A reward for every step.',
    balance: 'Welfare balance', balanceHint: 'Exchange 1:1 for account balance anytime', draws: 'Draws available', drawsUnit: 'draws', totalDays: 'Total check-ins', daysUnit: 'days', cycle: '{days} consecutive days this cycle', threshold: 'One draw per {amount} spent',
    rules: 'Program rules', probabilities: 'Prize probabilities', close: 'Got it', loading: 'Loading…', retry: 'Retry', processing: 'Processing…', paused: 'Check-ins and draws are paused. You can still redeem existing welfare funds.',
    checkIn: 'Daily check-in', checkNow: 'Check in now', checked: 'Checked in today', surprise: 'Check in to reveal today’s surprise', calendar: 'Check-in calendar', prevMonth: 'Previous month', nextMonth: 'Next month', today: 'Today', signed: 'Checked in', notSigned: 'Not checked in', calendarTimezone: 'Resets at midnight Beijing time', weekdays: 'Mon Tue Wed Thu Fri Sat Sun', milestone: '{days} consecutive days', mystery: 'Mystery reward', claimed: 'Credited', unlocked: 'Check in to reveal', remainingDays: '{days} days to go',
    checkSuccess: 'Checked in! Daily reward {daily}, streak reward {streak}; {total} credited to welfare balance.', checkDailySuccess: 'Checked in! {amount} credited to welfare balance.',
    lottery: 'Free prize draw', availableDraws: 'Available draws', guaranteed: 'Every draw earns welfare funds', progress: 'Progress toward your next draw', spendRemaining: 'Spend {amount} more to earn one draw', drawNow: 'Draw now · Uses one draw', noDraws: 'No draws available', prizePool: 'Prize pool', debt: 'Draws to offset: {count}', drawResult: 'Your prize', received: 'Welfare funds earned', drawSuccess: 'Credited to welfare balance. {count} draws remaining.', accept: 'Collect reward',
    redemption: 'Redeem welfare', redeemable: 'Available welfare balance', redeem: 'Redeem balance', exchangeNote: '1:1 to account balance · No fees', redemptionTitle: 'Redeem to account balance', amount: 'Amount', all: 'All', quote: 'Preview redemption', confirm: 'Confirm redemption', cancel: 'Cancel', rate: 'Exchange rate', rateValue: '1:1 · No fees', accountAfter: 'Account balance after redemption', redemptionHint: 'Redeem any available amount in $0.01 increments. Funds transfer immediately on confirmation.', invalidAmount: 'Enter an amount greater than zero with up to two decimal places.', insufficient: 'Amount exceeds your available welfare balance.', redemptionSuccess: '{amount} transferred to account balance.', retryTransfer: 'Retry this redemption', uncertainTransfer: 'The redemption result has not arrived. Retry to confirm this transfer; you will not be charged twice.',
    records: 'Welfare history', totalDraws: '{count} total draws', recordType: 'Record type', from: 'Start date', to: 'End date', reset: 'Reset', time: 'Time', type: 'Type', detail: 'Details', change: 'Welfare balance change', recordCount: '{count} records', prevPage: 'Previous page', nextPage: 'Next page', empty: 'No welfare records match these filters', footer: '30-day cycles · Missed days reset your streak · No backdating · Redeem welfare 1:1 for account balance',
    types: { all: 'All types', daily: 'Daily check-in', streak: 'Streak reward', draw: 'Prize draw', redeem: 'Redemption' },
    ruleCheck: 'Check in once a day to reveal your reward. Each day resets at midnight Beijing time. Missed days cannot be backdated.', ruleStreak: 'Mystery rewards unlock on consecutive days 7, 15 and 30, with the amount revealed when credited. After day 30, a new cycle begins. Missing a day resets the streak while total check-ins remain.', ruleSpend: 'Once the program opens, every {amount} in actual API account-balance charges earns one draw. Remaining spend carries forward. Top-ups and usage covered by subscriptions do not count.', ruleRedeem: 'Check-in and draw rewards enter your welfare balance. Redeem part or all of it 1:1 to account balance without fees.', probabilityHint: 'Each draw is independent. Every prize is credited to welfare balance.',
    errors: { WELFARE_STORAGE_UNAVAILABLE: 'Operation progress could not be saved. Allow browser storage and retry.', WELFARE_OPERATION_UNRESOLVED: 'Your previous redemption is unresolved. Retry that transfer first.', network: 'The latest result is temporarily unavailable. Please retry.', dateRange: 'Start date must not be later than end date.', WELFARE_PAUSED: 'Rewards are paused. Existing welfare funds can still be redeemed.', WELFARE_NOT_LAUNCHED: 'The welfare program has not opened yet.', WELFARE_NO_TICKETS: 'No draws are available. Refresh and try again.', WELFARE_QUOTE_STALE: 'Your welfare balance changed. Preview the updated amount before confirming.', WELFARE_INSUFFICIENT_BALANCE: 'Insufficient welfare balance. Preview the updated amount.', WELFARE_IDEMPOTENCY_CONFLICT: 'Operation details do not match. Refresh and retry.', WELFARE_INVALID_AMOUNT: 'Enter a valid redemption amount.', WELFARE_INVALID_REQUEST: 'Invalid request. Refresh and retry.' },
    admin: { title: 'Welfare management', description: 'Manage welfare program availability', program: 'Program status', enabledLabel: 'Enable check-ins, draws and spend rewards', enabledHint: 'While paused, users can still redeem existing welfare funds and view records.', launchAt: 'First launch', notLaunched: 'Not launched', timezone: 'Program timezone', rulesVersion: 'Reward rules version', launchHint: 'Spending accrues from the first enable; earlier spending is excluded. Re-enabling preserves balances and progress.', saved: 'Welfare settings saved', loadFailed: 'Failed to load welfare settings', saveFailed: 'Failed to save welfare settings' }
  }
}
