// Code generated by ent, DO NOT EDIT.

package subscriptiondailyresetevent

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the subscriptiondailyresetevent type in the database.
	Label = "subscription_daily_reset_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldOperationID holds the string denoting the operation_id field in the database.
	FieldOperationID = "operation_id"
	// FieldRequestFingerprint holds the string denoting the request_fingerprint field in the database.
	FieldRequestFingerprint = "request_fingerprint"
	// FieldBeforeVersion holds the string denoting the before_version field in the database.
	FieldBeforeVersion = "before_version"
	// FieldAfterVersion holds the string denoting the after_version field in the database.
	FieldAfterVersion = "after_version"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// FieldCountDate holds the string denoting the count_date field in the database.
	FieldCountDate = "count_date"
	// FieldDaySequence holds the string denoting the day_sequence field in the database.
	FieldDaySequence = "day_sequence"
	// FieldBeforeDailyUsageUsd holds the string denoting the before_daily_usage_usd field in the database.
	FieldBeforeDailyUsageUsd = "before_daily_usage_usd"
	// FieldAfterDailyUsageUsd holds the string denoting the after_daily_usage_usd field in the database.
	FieldAfterDailyUsageUsd = "after_daily_usage_usd"
	// FieldDailyLimitUsd holds the string denoting the daily_limit_usd field in the database.
	FieldDailyLimitUsd = "daily_limit_usd"
	// FieldBeforeExpiresAt holds the string denoting the before_expires_at field in the database.
	FieldBeforeExpiresAt = "before_expires_at"
	// FieldAfterExpiresAt holds the string denoting the after_expires_at field in the database.
	FieldAfterExpiresAt = "after_expires_at"
	// FieldDeductedSeconds holds the string denoting the deducted_seconds field in the database.
	FieldDeductedSeconds = "deducted_seconds"
	// FieldDecidedAt holds the string denoting the decided_at field in the database.
	FieldDecidedAt = "decided_at"
	// Table holds the table name of the subscriptiondailyresetevent in the database.
	Table = "subscription_daily_reset_events"
)

// Columns holds all SQL columns for subscriptiondailyresetevent fields.
var Columns = []string{
	FieldID,
	FieldSubscriptionID,
	FieldUserID,
	FieldGroupID,
	FieldSource,
	FieldOperationID,
	FieldRequestFingerprint,
	FieldBeforeVersion,
	FieldAfterVersion,
	FieldTimezone,
	FieldCountDate,
	FieldDaySequence,
	FieldBeforeDailyUsageUsd,
	FieldAfterDailyUsageUsd,
	FieldDailyLimitUsd,
	FieldBeforeExpiresAt,
	FieldAfterExpiresAt,
	FieldDeductedSeconds,
	FieldDecidedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// OperationIDValidator is a validator for the "operation_id" field. It is called by the builders before save.
	OperationIDValidator func(string) error
	// RequestFingerprintValidator is a validator for the "request_fingerprint" field. It is called by the builders before save.
	RequestFingerprintValidator func(string) error
	// BeforeVersionValidator is a validator for the "before_version" field. It is called by the builders before save.
	BeforeVersionValidator func(int64) error
	// AfterVersionValidator is a validator for the "after_version" field. It is called by the builders before save.
	AfterVersionValidator func(int64) error
	// TimezoneValidator is a validator for the "timezone" field. It is called by the builders before save.
	TimezoneValidator func(string) error
	// DaySequenceValidator is a validator for the "day_sequence" field. It is called by the builders before save.
	DaySequenceValidator func(int) error
	// DefaultAfterDailyUsageUsd holds the default value on creation for the "after_daily_usage_usd" field.
	DefaultAfterDailyUsageUsd float64
	// DefaultDeductedSeconds holds the default value on creation for the "deducted_seconds" field.
	DefaultDeductedSeconds int
)

// OrderOption defines the ordering options for the SubscriptionDailyResetEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByOperationID orders the results by the operation_id field.
func ByOperationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperationID, opts...).ToFunc()
}

// ByRequestFingerprint orders the results by the request_fingerprint field.
func ByRequestFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestFingerprint, opts...).ToFunc()
}

// ByBeforeVersion orders the results by the before_version field.
func ByBeforeVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBeforeVersion, opts...).ToFunc()
}

// ByAfterVersion orders the results by the after_version field.
func ByAfterVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAfterVersion, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByCountDate orders the results by the count_date field.
func ByCountDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountDate, opts...).ToFunc()
}

// ByDaySequence orders the results by the day_sequence field.
func ByDaySequence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDaySequence, opts...).ToFunc()
}

// ByBeforeDailyUsageUsd orders the results by the before_daily_usage_usd field.
func ByBeforeDailyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBeforeDailyUsageUsd, opts...).ToFunc()
}

// ByAfterDailyUsageUsd orders the results by the after_daily_usage_usd field.
func ByAfterDailyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAfterDailyUsageUsd, opts...).ToFunc()
}

// ByDailyLimitUsd orders the results by the daily_limit_usd field.
func ByDailyLimitUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyLimitUsd, opts...).ToFunc()
}

// ByBeforeExpiresAt orders the results by the before_expires_at field.
func ByBeforeExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBeforeExpiresAt, opts...).ToFunc()
}

// ByAfterExpiresAt orders the results by the after_expires_at field.
func ByAfterExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAfterExpiresAt, opts...).ToFunc()
}

// ByDeductedSeconds orders the results by the deducted_seconds field.
func ByDeductedSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeductedSeconds, opts...).ToFunc()
}

// ByDecidedAt orders the results by the decided_at field.
func ByDecidedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDecidedAt, opts...).ToFunc()
}
