// Code generated by ent, DO NOT EDIT.

package subscriptiondailyresetevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldID, id))
}

// SubscriptionID applies equality check predicate on the "subscription_id" field. It's identical to SubscriptionIDEQ.
func SubscriptionID(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldSubscriptionID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldGroupID, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldSource, v))
}

// OperationID applies equality check predicate on the "operation_id" field. It's identical to OperationIDEQ.
func OperationID(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldOperationID, v))
}

// RequestFingerprint applies equality check predicate on the "request_fingerprint" field. It's identical to RequestFingerprintEQ.
func RequestFingerprint(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldRequestFingerprint, v))
}

// BeforeVersion applies equality check predicate on the "before_version" field. It's identical to BeforeVersionEQ.
func BeforeVersion(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldBeforeVersion, v))
}

// AfterVersion applies equality check predicate on the "after_version" field. It's identical to AfterVersionEQ.
func AfterVersion(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldAfterVersion, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldTimezone, v))
}

// CountDate applies equality check predicate on the "count_date" field. It's identical to CountDateEQ.
func CountDate(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldCountDate, v))
}

// DaySequence applies equality check predicate on the "day_sequence" field. It's identical to DaySequenceEQ.
func DaySequence(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldDaySequence, v))
}

// BeforeDailyUsageUsd applies equality check predicate on the "before_daily_usage_usd" field. It's identical to BeforeDailyUsageUsdEQ.
func BeforeDailyUsageUsd(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldBeforeDailyUsageUsd, v))
}

// AfterDailyUsageUsd applies equality check predicate on the "after_daily_usage_usd" field. It's identical to AfterDailyUsageUsdEQ.
func AfterDailyUsageUsd(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldAfterDailyUsageUsd, v))
}

// DailyLimitUsd applies equality check predicate on the "daily_limit_usd" field. It's identical to DailyLimitUsdEQ.
func DailyLimitUsd(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// BeforeExpiresAt applies equality check predicate on the "before_expires_at" field. It's identical to BeforeExpiresAtEQ.
func BeforeExpiresAt(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldBeforeExpiresAt, v))
}

// AfterExpiresAt applies equality check predicate on the "after_expires_at" field. It's identical to AfterExpiresAtEQ.
func AfterExpiresAt(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldAfterExpiresAt, v))
}

// DeductedSeconds applies equality check predicate on the "deducted_seconds" field. It's identical to DeductedSecondsEQ.
func DeductedSeconds(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldDeductedSeconds, v))
}

// DecidedAt applies equality check predicate on the "decided_at" field. It's identical to DecidedAtEQ.
func DecidedAt(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldDecidedAt, v))
}

// SubscriptionIDEQ applies the EQ predicate on the "subscription_id" field.
func SubscriptionIDEQ(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldSubscriptionID, v))
}

// SubscriptionIDNEQ applies the NEQ predicate on the "subscription_id" field.
func SubscriptionIDNEQ(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldSubscriptionID, v))
}

// SubscriptionIDIn applies the In predicate on the "subscription_id" field.
func SubscriptionIDIn(vs ...int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDNotIn applies the NotIn predicate on the "subscription_id" field.
func SubscriptionIDNotIn(vs ...int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldSubscriptionID, vs...))
}

// SubscriptionIDGT applies the GT predicate on the "subscription_id" field.
func SubscriptionIDGT(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldSubscriptionID, v))
}

// SubscriptionIDGTE applies the GTE predicate on the "subscription_id" field.
func SubscriptionIDGTE(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldSubscriptionID, v))
}

// SubscriptionIDLT applies the LT predicate on the "subscription_id" field.
func SubscriptionIDLT(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldSubscriptionID, v))
}

// SubscriptionIDLTE applies the LTE predicate on the "subscription_id" field.
func SubscriptionIDLTE(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldSubscriptionID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldUserID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldGroupID, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldContainsFold(FieldSource, v))
}

// OperationIDEQ applies the EQ predicate on the "operation_id" field.
func OperationIDEQ(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldOperationID, v))
}

// OperationIDNEQ applies the NEQ predicate on the "operation_id" field.
func OperationIDNEQ(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldOperationID, v))
}

// OperationIDIn applies the In predicate on the "operation_id" field.
func OperationIDIn(vs ...string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldOperationID, vs...))
}

// OperationIDNotIn applies the NotIn predicate on the "operation_id" field.
func OperationIDNotIn(vs ...string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldOperationID, vs...))
}

// OperationIDGT applies the GT predicate on the "operation_id" field.
func OperationIDGT(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldOperationID, v))
}

// OperationIDGTE applies the GTE predicate on the "operation_id" field.
func OperationIDGTE(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldOperationID, v))
}

// OperationIDLT applies the LT predicate on the "operation_id" field.
func OperationIDLT(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldOperationID, v))
}

// OperationIDLTE applies the LTE predicate on the "operation_id" field.
func OperationIDLTE(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldOperationID, v))
}

// OperationIDContains applies the Contains predicate on the "operation_id" field.
func OperationIDContains(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldContains(FieldOperationID, v))
}

// OperationIDHasPrefix applies the HasPrefix predicate on the "operation_id" field.
func OperationIDHasPrefix(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldHasPrefix(FieldOperationID, v))
}

// OperationIDHasSuffix applies the HasSuffix predicate on the "operation_id" field.
func OperationIDHasSuffix(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldHasSuffix(FieldOperationID, v))
}

// OperationIDEqualFold applies the EqualFold predicate on the "operation_id" field.
func OperationIDEqualFold(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEqualFold(FieldOperationID, v))
}

// OperationIDContainsFold applies the ContainsFold predicate on the "operation_id" field.
func OperationIDContainsFold(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldContainsFold(FieldOperationID, v))
}

// RequestFingerprintEQ applies the EQ predicate on the "request_fingerprint" field.
func RequestFingerprintEQ(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintNEQ applies the NEQ predicate on the "request_fingerprint" field.
func RequestFingerprintNEQ(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintIn applies the In predicate on the "request_fingerprint" field.
func RequestFingerprintIn(vs ...string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintNotIn applies the NotIn predicate on the "request_fingerprint" field.
func RequestFingerprintNotIn(vs ...string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintGT applies the GT predicate on the "request_fingerprint" field.
func RequestFingerprintGT(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldRequestFingerprint, v))
}

// RequestFingerprintGTE applies the GTE predicate on the "request_fingerprint" field.
func RequestFingerprintGTE(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldRequestFingerprint, v))
}

// RequestFingerprintLT applies the LT predicate on the "request_fingerprint" field.
func RequestFingerprintLT(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldRequestFingerprint, v))
}

// RequestFingerprintLTE applies the LTE predicate on the "request_fingerprint" field.
func RequestFingerprintLTE(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldRequestFingerprint, v))
}

// RequestFingerprintContains applies the Contains predicate on the "request_fingerprint" field.
func RequestFingerprintContains(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldContains(FieldRequestFingerprint, v))
}

// RequestFingerprintHasPrefix applies the HasPrefix predicate on the "request_fingerprint" field.
func RequestFingerprintHasPrefix(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldHasPrefix(FieldRequestFingerprint, v))
}

// RequestFingerprintHasSuffix applies the HasSuffix predicate on the "request_fingerprint" field.
func RequestFingerprintHasSuffix(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldHasSuffix(FieldRequestFingerprint, v))
}

// RequestFingerprintEqualFold applies the EqualFold predicate on the "request_fingerprint" field.
func RequestFingerprintEqualFold(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEqualFold(FieldRequestFingerprint, v))
}

// RequestFingerprintContainsFold applies the ContainsFold predicate on the "request_fingerprint" field.
func RequestFingerprintContainsFold(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldContainsFold(FieldRequestFingerprint, v))
}

// BeforeVersionEQ applies the EQ predicate on the "before_version" field.
func BeforeVersionEQ(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldBeforeVersion, v))
}

// BeforeVersionNEQ applies the NEQ predicate on the "before_version" field.
func BeforeVersionNEQ(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldBeforeVersion, v))
}

// BeforeVersionIn applies the In predicate on the "before_version" field.
func BeforeVersionIn(vs ...int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldBeforeVersion, vs...))
}

// BeforeVersionNotIn applies the NotIn predicate on the "before_version" field.
func BeforeVersionNotIn(vs ...int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldBeforeVersion, vs...))
}

// BeforeVersionGT applies the GT predicate on the "before_version" field.
func BeforeVersionGT(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldBeforeVersion, v))
}

// BeforeVersionGTE applies the GTE predicate on the "before_version" field.
func BeforeVersionGTE(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldBeforeVersion, v))
}

// BeforeVersionLT applies the LT predicate on the "before_version" field.
func BeforeVersionLT(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldBeforeVersion, v))
}

// BeforeVersionLTE applies the LTE predicate on the "before_version" field.
func BeforeVersionLTE(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldBeforeVersion, v))
}

// AfterVersionEQ applies the EQ predicate on the "after_version" field.
func AfterVersionEQ(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldAfterVersion, v))
}

// AfterVersionNEQ applies the NEQ predicate on the "after_version" field.
func AfterVersionNEQ(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldAfterVersion, v))
}

// AfterVersionIn applies the In predicate on the "after_version" field.
func AfterVersionIn(vs ...int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldAfterVersion, vs...))
}

// AfterVersionNotIn applies the NotIn predicate on the "after_version" field.
func AfterVersionNotIn(vs ...int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldAfterVersion, vs...))
}

// AfterVersionGT applies the GT predicate on the "after_version" field.
func AfterVersionGT(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldAfterVersion, v))
}

// AfterVersionGTE applies the GTE predicate on the "after_version" field.
func AfterVersionGTE(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldAfterVersion, v))
}

// AfterVersionLT applies the LT predicate on the "after_version" field.
func AfterVersionLT(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldAfterVersion, v))
}

// AfterVersionLTE applies the LTE predicate on the "after_version" field.
func AfterVersionLTE(v int64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldAfterVersion, v))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldContainsFold(FieldTimezone, v))
}

// CountDateEQ applies the EQ predicate on the "count_date" field.
func CountDateEQ(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldCountDate, v))
}

// CountDateNEQ applies the NEQ predicate on the "count_date" field.
func CountDateNEQ(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldCountDate, v))
}

// CountDateIn applies the In predicate on the "count_date" field.
func CountDateIn(vs ...time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldCountDate, vs...))
}

// CountDateNotIn applies the NotIn predicate on the "count_date" field.
func CountDateNotIn(vs ...time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldCountDate, vs...))
}

// CountDateGT applies the GT predicate on the "count_date" field.
func CountDateGT(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldCountDate, v))
}

// CountDateGTE applies the GTE predicate on the "count_date" field.
func CountDateGTE(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldCountDate, v))
}

// CountDateLT applies the LT predicate on the "count_date" field.
func CountDateLT(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldCountDate, v))
}

// CountDateLTE applies the LTE predicate on the "count_date" field.
func CountDateLTE(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldCountDate, v))
}

// DaySequenceEQ applies the EQ predicate on the "day_sequence" field.
func DaySequenceEQ(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldDaySequence, v))
}

// DaySequenceNEQ applies the NEQ predicate on the "day_sequence" field.
func DaySequenceNEQ(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldDaySequence, v))
}

// DaySequenceIn applies the In predicate on the "day_sequence" field.
func DaySequenceIn(vs ...int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldDaySequence, vs...))
}

// DaySequenceNotIn applies the NotIn predicate on the "day_sequence" field.
func DaySequenceNotIn(vs ...int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldDaySequence, vs...))
}

// DaySequenceGT applies the GT predicate on the "day_sequence" field.
func DaySequenceGT(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldDaySequence, v))
}

// DaySequenceGTE applies the GTE predicate on the "day_sequence" field.
func DaySequenceGTE(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldDaySequence, v))
}

// DaySequenceLT applies the LT predicate on the "day_sequence" field.
func DaySequenceLT(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldDaySequence, v))
}

// DaySequenceLTE applies the LTE predicate on the "day_sequence" field.
func DaySequenceLTE(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldDaySequence, v))
}

// BeforeDailyUsageUsdEQ applies the EQ predicate on the "before_daily_usage_usd" field.
func BeforeDailyUsageUsdEQ(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldBeforeDailyUsageUsd, v))
}

// BeforeDailyUsageUsdNEQ applies the NEQ predicate on the "before_daily_usage_usd" field.
func BeforeDailyUsageUsdNEQ(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldBeforeDailyUsageUsd, v))
}

// BeforeDailyUsageUsdIn applies the In predicate on the "before_daily_usage_usd" field.
func BeforeDailyUsageUsdIn(vs ...float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldBeforeDailyUsageUsd, vs...))
}

// BeforeDailyUsageUsdNotIn applies the NotIn predicate on the "before_daily_usage_usd" field.
func BeforeDailyUsageUsdNotIn(vs ...float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldBeforeDailyUsageUsd, vs...))
}

// BeforeDailyUsageUsdGT applies the GT predicate on the "before_daily_usage_usd" field.
func BeforeDailyUsageUsdGT(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldBeforeDailyUsageUsd, v))
}

// BeforeDailyUsageUsdGTE applies the GTE predicate on the "before_daily_usage_usd" field.
func BeforeDailyUsageUsdGTE(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldBeforeDailyUsageUsd, v))
}

// BeforeDailyUsageUsdLT applies the LT predicate on the "before_daily_usage_usd" field.
func BeforeDailyUsageUsdLT(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldBeforeDailyUsageUsd, v))
}

// BeforeDailyUsageUsdLTE applies the LTE predicate on the "before_daily_usage_usd" field.
func BeforeDailyUsageUsdLTE(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldBeforeDailyUsageUsd, v))
}

// AfterDailyUsageUsdEQ applies the EQ predicate on the "after_daily_usage_usd" field.
func AfterDailyUsageUsdEQ(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldAfterDailyUsageUsd, v))
}

// AfterDailyUsageUsdNEQ applies the NEQ predicate on the "after_daily_usage_usd" field.
func AfterDailyUsageUsdNEQ(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldAfterDailyUsageUsd, v))
}

// AfterDailyUsageUsdIn applies the In predicate on the "after_daily_usage_usd" field.
func AfterDailyUsageUsdIn(vs ...float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldAfterDailyUsageUsd, vs...))
}

// AfterDailyUsageUsdNotIn applies the NotIn predicate on the "after_daily_usage_usd" field.
func AfterDailyUsageUsdNotIn(vs ...float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldAfterDailyUsageUsd, vs...))
}

// AfterDailyUsageUsdGT applies the GT predicate on the "after_daily_usage_usd" field.
func AfterDailyUsageUsdGT(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldAfterDailyUsageUsd, v))
}

// AfterDailyUsageUsdGTE applies the GTE predicate on the "after_daily_usage_usd" field.
func AfterDailyUsageUsdGTE(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldAfterDailyUsageUsd, v))
}

// AfterDailyUsageUsdLT applies the LT predicate on the "after_daily_usage_usd" field.
func AfterDailyUsageUsdLT(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldAfterDailyUsageUsd, v))
}

// AfterDailyUsageUsdLTE applies the LTE predicate on the "after_daily_usage_usd" field.
func AfterDailyUsageUsdLTE(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldAfterDailyUsageUsd, v))
}

// DailyLimitUsdEQ applies the EQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdEQ(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdNEQ applies the NEQ predicate on the "daily_limit_usd" field.
func DailyLimitUsdNEQ(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldDailyLimitUsd, v))
}

// DailyLimitUsdIn applies the In predicate on the "daily_limit_usd" field.
func DailyLimitUsdIn(vs ...float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdNotIn applies the NotIn predicate on the "daily_limit_usd" field.
func DailyLimitUsdNotIn(vs ...float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldDailyLimitUsd, vs...))
}

// DailyLimitUsdGT applies the GT predicate on the "daily_limit_usd" field.
func DailyLimitUsdGT(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdGTE applies the GTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdGTE(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLT applies the LT predicate on the "daily_limit_usd" field.
func DailyLimitUsdLT(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldDailyLimitUsd, v))
}

// DailyLimitUsdLTE applies the LTE predicate on the "daily_limit_usd" field.
func DailyLimitUsdLTE(v float64) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldDailyLimitUsd, v))
}

// BeforeExpiresAtEQ applies the EQ predicate on the "before_expires_at" field.
func BeforeExpiresAtEQ(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldBeforeExpiresAt, v))
}

// BeforeExpiresAtNEQ applies the NEQ predicate on the "before_expires_at" field.
func BeforeExpiresAtNEQ(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldBeforeExpiresAt, v))
}

// BeforeExpiresAtIn applies the In predicate on the "before_expires_at" field.
func BeforeExpiresAtIn(vs ...time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldBeforeExpiresAt, vs...))
}

// BeforeExpiresAtNotIn applies the NotIn predicate on the "before_expires_at" field.
func BeforeExpiresAtNotIn(vs ...time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldBeforeExpiresAt, vs...))
}

// BeforeExpiresAtGT applies the GT predicate on the "before_expires_at" field.
func BeforeExpiresAtGT(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldBeforeExpiresAt, v))
}

// BeforeExpiresAtGTE applies the GTE predicate on the "before_expires_at" field.
func BeforeExpiresAtGTE(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldBeforeExpiresAt, v))
}

// BeforeExpiresAtLT applies the LT predicate on the "before_expires_at" field.
func BeforeExpiresAtLT(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldBeforeExpiresAt, v))
}

// BeforeExpiresAtLTE applies the LTE predicate on the "before_expires_at" field.
func BeforeExpiresAtLTE(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldBeforeExpiresAt, v))
}

// AfterExpiresAtEQ applies the EQ predicate on the "after_expires_at" field.
func AfterExpiresAtEQ(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldAfterExpiresAt, v))
}

// AfterExpiresAtNEQ applies the NEQ predicate on the "after_expires_at" field.
func AfterExpiresAtNEQ(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldAfterExpiresAt, v))
}

// AfterExpiresAtIn applies the In predicate on the "after_expires_at" field.
func AfterExpiresAtIn(vs ...time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldAfterExpiresAt, vs...))
}

// AfterExpiresAtNotIn applies the NotIn predicate on the "after_expires_at" field.
func AfterExpiresAtNotIn(vs ...time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldAfterExpiresAt, vs...))
}

// AfterExpiresAtGT applies the GT predicate on the "after_expires_at" field.
func AfterExpiresAtGT(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldAfterExpiresAt, v))
}

// AfterExpiresAtGTE applies the GTE predicate on the "after_expires_at" field.
func AfterExpiresAtGTE(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldAfterExpiresAt, v))
}

// AfterExpiresAtLT applies the LT predicate on the "after_expires_at" field.
func AfterExpiresAtLT(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldAfterExpiresAt, v))
}

// AfterExpiresAtLTE applies the LTE predicate on the "after_expires_at" field.
func AfterExpiresAtLTE(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldAfterExpiresAt, v))
}

// DeductedSecondsEQ applies the EQ predicate on the "deducted_seconds" field.
func DeductedSecondsEQ(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldDeductedSeconds, v))
}

// DeductedSecondsNEQ applies the NEQ predicate on the "deducted_seconds" field.
func DeductedSecondsNEQ(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldDeductedSeconds, v))
}

// DeductedSecondsIn applies the In predicate on the "deducted_seconds" field.
func DeductedSecondsIn(vs ...int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldDeductedSeconds, vs...))
}

// DeductedSecondsNotIn applies the NotIn predicate on the "deducted_seconds" field.
func DeductedSecondsNotIn(vs ...int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldDeductedSeconds, vs...))
}

// DeductedSecondsGT applies the GT predicate on the "deducted_seconds" field.
func DeductedSecondsGT(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldDeductedSeconds, v))
}

// DeductedSecondsGTE applies the GTE predicate on the "deducted_seconds" field.
func DeductedSecondsGTE(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldDeductedSeconds, v))
}

// DeductedSecondsLT applies the LT predicate on the "deducted_seconds" field.
func DeductedSecondsLT(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldDeductedSeconds, v))
}

// DeductedSecondsLTE applies the LTE predicate on the "deducted_seconds" field.
func DeductedSecondsLTE(v int) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldDeductedSeconds, v))
}

// DecidedAtEQ applies the EQ predicate on the "decided_at" field.
func DecidedAtEQ(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldEQ(FieldDecidedAt, v))
}

// DecidedAtNEQ applies the NEQ predicate on the "decided_at" field.
func DecidedAtNEQ(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNEQ(FieldDecidedAt, v))
}

// DecidedAtIn applies the In predicate on the "decided_at" field.
func DecidedAtIn(vs ...time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldIn(FieldDecidedAt, vs...))
}

// DecidedAtNotIn applies the NotIn predicate on the "decided_at" field.
func DecidedAtNotIn(vs ...time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldNotIn(FieldDecidedAt, vs...))
}

// DecidedAtGT applies the GT predicate on the "decided_at" field.
func DecidedAtGT(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGT(FieldDecidedAt, v))
}

// DecidedAtGTE applies the GTE predicate on the "decided_at" field.
func DecidedAtGTE(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldGTE(FieldDecidedAt, v))
}

// DecidedAtLT applies the LT predicate on the "decided_at" field.
func DecidedAtLT(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLT(FieldDecidedAt, v))
}

// DecidedAtLTE applies the LTE predicate on the "decided_at" field.
func DecidedAtLTE(v time.Time) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.FieldLTE(FieldDecidedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionDailyResetEvent) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionDailyResetEvent) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionDailyResetEvent) predicate.SubscriptionDailyResetEvent {
	return predicate.SubscriptionDailyResetEvent(sql.NotPredicates(p))
}
